config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :customers
  resources :employees

  post 'employees/create' => 'employees#create'
  post 'employees/logout' => 'employees#logout'
  post 'employees/login' => 'employees#login'
  post 'employees/view_schedule' => 'employees#view_schedule'
  post 'employees/make_schedule' => 'employees#make_schedule'
  post 'employees/rent' => 'employees#rent'
  post 'employees/change_password' => 'employees#change_password'
  post 'employees/change_phone_number' => 'employees#change_phone_number'
  post 'employees/change_email' => 'employees#change_email'
  post 'employees/edit_first_name' => 'employees#edit_first_name'
  post 'employees/edit_last_name' => 'employees#edit_last_name'
  post 'employees/forgot_password' => 'employees#edit_forgot_password'

  post 'customers/create' => 'customers#create'
  post 'customers/login' => 'customers#login'
  post 'customers/logout' => 'customers#logout'
  post 'customers/rent_history' => 'customers#rent_history'
  post 'customers/rent' => 'customers#rent'
  post 'customers/change_password' => 'customers#change_password'
  post 'customers/change_phone_number' => 'customers#change_phone_number'
  post 'customers/change_email' => 'customers#change_email'
  post 'customers/edit_first_name' => 'customers#edit_first_name'
  post 'customers/edit_last_name' => 'customers#edit_last_name'
  post 'customers/forgot_password' => 'customers#edit_forgot_password'

end

#   end

app/models/employee.rb
class Employee < ActiveRecord::Base
  require 'json'
  respond_to? 'json'
  belongs_to :user
  validates_presence_of :user_id, :rank, :status, :social_security, :salary

  def Employee.create_employee(employee, user, address)
    this_user_info = User.create_user(user, address)
    this_user_info[:code] == true ? (
    user = this_user_info[:data][:user]
    this_employee = Employee.new(user_id: user.id)
    this_employee.update_attributes(employee)
    this_employee.save
    new_address = Address.create_address(user.id, type = 'employee', address)
    if new_address.save
      return new_user = { code: true, data:{remember_token: RememberToken.sign_in(this_employee),
                                            user: user, employee: this_employee, :address => new_address}}
    else
      return new_user = { code: true, data:{remember_token: RememberToken.sign_in(this_employee),
                                            user: user, employee: this_employee, :address => 'address not created.'}}
    end)
    : ( return error = {code: false, data: this_employee.errors.full_messages})
  end

  def view_employee_schedule
    schedule = WorkSchedule.where(:employee_id => self.id).first
    schedule ? (return work = {code: true, data: schedule})
    : ( return work_schedule = {code: false, data: 'no schedule'})
  end

  def create_employee_schedule(credentials)
    this_employee = Employee.find_by_id(credentials[:employee_id])
    if this_employee
      if this_employee.status != 'invalid' && ( self.rank == 'owner' || self.rank == 'manager')
        new_schedule = WorkSchedule.new(credentials)
        new_schedule.update_attributes(:start_date => Date.today.beginning_of_day + 7.days,
                                       :end_date => Date.today.end_of_day + 7.days)
         new_schedule.save ? (
         return schedule = {code: true, data: new_schedule})
        : (
         return schedule = {code: false, data: new_schedule.errors.full_messages})
      else
        return schedule = {code: false, data: 'employee status invalid or you are not authorized'}
      end
    else
      return schedule = {code: false, data: 'employee not found'}
    end
  end

  def update_employee_schedule(parameters)
    this_employee = Employee.find_by_id(parameters[:id])
    if self.rank == 'owner' || self.rank == 'manager'
      if this_employee
        schedule = WorkSchedule.where(employee_id: this_employee.id).first
        schedule ? (
          schedule.update_attributes(parameters)
          schedule.save
           return update_schedule = {code: true, data: schedule})
        : (
        return update_schedule ={code: false, data: 'no schedule found'}
        )
        end
        return update_schedule ={code: false, data: 'no employee found'}
      end
      return update_schedule = {code: false, data: 'you are not authorized'}
  end

  def employee_rent(isbn)
    this_employee = Employee.find_by_id(isbn[:employee_id])
    this_employee.account_status != 'invalid'? (
        book = Book.find_by_id(isbn[:book_id])
        new_rent = Rent.new(employee_id: self.id, due_date: book.manage_return_day, book_id: book.id,
                            due: book.rent_price, rent_condition: book.condition, employee_id: this_employee.id)
        new_rent.save
        return rents = {code: true, data: new_rent})
    : (
    return rents = {code: false, data: 'employee status invalid'})
  end

  def return_book(employee, rent, return_params)
    this_employee = Employee.find_by_id(employee)
    if this_employee
      rent = Rent.find_by_id(rent)
      rent ? (
        rent.update_attributes(returned: true, return_date: Time.now,
                               fined: rent.fined_method, rent_condition: return_params[:rent_condition])
        this_book = Book.find_by_id(rent.book_id)
        this_book.update_attributes(condition: rent.rent_condition, times_rented: this_book.times_rented + 1)
        return hash = {code: true, data: {book: this_book, rent: rent}})
      : (
      return hash = {code: false, data: 'no rent found'}
      )
    else
      return hash  = {code: false, data: 'employee not in the system.'}
    end
  end

end

app/controllers/employees_controller.rb
class EmployeesController < UsersController
  require 'json'
  respond_to 'json'
  skip_before_filter  :verify_authenticity_token
  before_action :auth_params, except: [:create, :login]
  before_action :authenticate, except: [:create, :login, :auth_params]
  #date format Sun, 15 Feb 2015

  def authenticate
      user = RememberToken.authenticate(RememberToken.digest(auth_params.slice[:remember_token]))
      user.instance_of?(User)? (@employee = Employee.find_by_user_id(user.id)) : (sender(error = {:code => false, :data => 'please login again.'}))
      @employee !=nil ? (return @employee) : (sender(error = {:code => false, :data => 'please login again.'}))
    end

  def create
    sender(new_employee = Employee.create_employee(employee_params, user_params, address_params))
  end


  def view_schedule
    sender(schedule = @employee.view_employee_schedule)
  end

  def make_schedule
    sender(new_schedule = @employee.create_employee_schedule(schedule_params))
  end

  def update_schedule
    sender(updated_schedule = @employee.update_employee_schedule(update_schedule_params))
  end

  def rent
    sender(new_rent = @employee.employee_rent(new_rent_params))
  end

  def book_return
    sender(returned = @employee.return(params[:id], params[:rent_id], return_params))
  end

  private

  def employee_params
    return nil unless params["employee"]
    params.require(:employee).permit(:rank, :status, :social_security, :salary)
  end

  def address_params
    return nil unless params["address"]
    params.require(:address).permit(:street, :city, :state, :zip, :country)
  end

  def new_rent_params
    return nil unless params["rent"]
    params.require(:rent).permit(:customer_id, :book_id )
  end

  def return_params
    return nil unless params["return"]
    params.require(:return).permit(:return_condition)
  end

  def schedule_params
    return nil unless params["schedule"]
    params.require(:schedule).permit!
  end

  def update_schedule_params
    return nil unless params["update"]
    params.require(:update).permit!
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.check_box :gender %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.text_field :rank %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.text_field :salary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Rank</th>
      <th>Salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.gender %></td>
        <td><%= employee.rank %></td>
        <td><%= employee.salary %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @employee.gender %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @employee.rank %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @employee.salary %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>