config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :customers
  resources :employees

  post 'employees/create' => 'employees#create'
  post 'employees/logout' => 'employees#logout'
  post 'employees/login' => 'employees#login'
  post 'employees/view_schedule' => 'employees#view_schedule'
  post 'employees/make_schedule' => 'employees#make_schedule'
  post 'employees/rent' => 'employees#rent'
  post 'employees/change_password' => 'employees#change_password'
  post 'employees/change_phone_number' => 'employees#change_phone_number'
  post 'employees/change_email' => 'employees#change_email'
  post 'employees/edit_first_name' => 'employees#edit_first_name'
  post 'employees/edit_last_name' => 'employees#edit_last_name'
  post 'employees/forgot_password' => 'employees#edit_forgot_password'

  post 'customers/create' => 'customers#create'
  post 'customers/login' => 'customers#login'
  post 'customers/logout' => 'customers#logout'
  post 'customers/rent_history' => 'customers#rent_history'
  post 'customers/rent' => 'customers#rent'
  post 'customers/change_password' => 'customers#change_password'
  post 'customers/change_phone_number' => 'customers#change_phone_number'
  post 'customers/change_email' => 'customers#change_email'
  post 'customers/edit_first_name' => 'customers#edit_first_name'
  post 'customers/edit_last_name' => 'customers#edit_last_name'
  post 'customers/forgot_password' => 'customers#edit_forgot_password'

end

#   end

app/models/customer.rb
class Customer < ActiveRecord::Base
  require 'json'
  respond_to? 'json'
  belongs_to :user
  validates_presence_of :user_id

  def Customer.create_customer(customer, user, address)
    this_user_info = User.create_user(user, address)
     this_user_info[:code] == true ? (
      user = this_user_info[:data][:user]
      this_customer = Customer.new(user_id: user.id)
      this_customer.update_attributes(customer)
      this_customer.save
      new_address = Address.create_address(user.id, type = 'customer', address)
      if new_address.save
      return new_user = { code: true, data:{remember_token: RememberToken.sign_in(this_customer),
                                            user: user, customer: this_customer, :address => new_address}}
      else
      return new_user = { code: true, data:{remember_token: RememberToken.sign_in(this_customer),
                                            user: user, customer: this_customer, :address => 'address not created.'}}
      end)
    : ( return error = {code: false, data: this_customer.errors.full_messages})
  end

  def view_rent_history
    history = Rent.where(customer_id: self.id)
     (history != [] || !history.empty?) ? (
     return rent_history = {code: true, data: history})
    : (return rent_history = {code: false, data: 'no history'})
  end

  def rent(isbn)
    this_customer = Customer.find_by_id(self.id)
     (this_customer && this_customer.account_status != 'invalid') ? (
      book = Book.find_by_id(isbn[:book_id])
      new_rent = Rent.new(employee_id: 9999, due_date: book.manage_return_day, book_id: book.id,
                          due: book.rent_price, rent_condition: book.condition, customer_id: this_customer.id)
      new_rent.save
      return rents = {code: true, data: new_rent})
    : (return rents = {code: false, data: 'customer status invalid or customer not found'})
  end
end

app/controllers/customers_controller.rb
class CustomersController < UsersController
  require 'json'
  respond_to 'json'
  require 'aws/ses'
  skip_before_filter  :verify_authenticity_token
  before_action :auth_params, except: [:create, :login]
  before_action :authenticate, except: [:create, :login, :auth_params]

  def authenticate
    user = RememberToken.authenticate(RememberToken.digest(auth_params.slice[:remember_token]))
    user.instance_of?(User)? (@customer = Customer.find_by_user_id(user.id)) : (sender(error = {code: false, data: 'please login again.'}))
    @customer !=nil ? (return @customer) : (sender(error = {code: false, data: 'please login again.'}))
  end

  def create
    sender(new_customer = Customer.create_customer(customer_params, user_params , address_params))
  end

  def rent_history
    sender(rent_history = @customer.view_rent_history)
  end

  def rent_book
    sender(new_rent = @customer.employee_rent(new_rent_params))
  end

  def credit_card_info

  end

  def upgrade_category
    #pay and upgrade the status
  end


  private

  def customer_params
    return nil unless params["customer"]
    params.require(:customer).permit(:account_type, :account_status)
  end

  def address_params
    return nil unless params["address"]
    params.require(:address).permit(:street, :city, :state, :zip, :country)
  end

  def new_rent_params
    return nil unless params["rent"]
    params.require(:rent).permit(:book_id )
  end


end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.check_box :gender %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.gender %></td>
        <td><%= customer.type %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @customer.gender %>
</p>

<p>
  <strong>Type:</strong>
  <%= @customer.type %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>